# fly.toml app configuration file generated for fragrant-smoke-6434 on 2023-08-09T10:16:43-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fragrant-smoke-6434"
primary_region = "gru"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
